### PR TITLE
remove deleted bin files from package.json

### PR DESCRIPTION
**Pull request by diasdavid**
fixes https://github.com/beaugunderson/ip-address/issues/44

### CODE REVIEW

**Comment by rolodato** [comment]
+1, this is breaking libnmap as well. For anyone depending on this library, you can use `npm install ---no-bin-links` as a workaround in the meantime.

**Comment by beaugunderson** [comment]
merged and released 5.8.4 thank you both and sorry for the trouble!

**Comment by diasdavid** [comment]
Thank you @beaugunderson !!

**Comment by diasdavid** [comment]
@gavinmcdermott this is fixed now :)

**Pull request merged**
