### PR TITLE
add non-string check

### PR DESCRIPTION
**Pull request by drahnieR**

### CODE REVIEW

**Comment by drahnieR** [comment]
@beaugunderson how's your opinion on this

**Comment by beaugunderson** [comment]
@drahnieR i like this; can you change the error message to note that the argument should be a string?

**Comment by drahnieR** [comment]
@beaugunderson done

**Comment by drahnieR** [comment]
@beaugunderson any chance that this could be released soon?

**Comment by beaugunderson** [comment]
we migrated away from lodash but this would still be useful if implemented in vanilla JS

**Pull request closed without merging**
